### ISSUE TITLE
Problem handling connection errors on OPCUA Compact Server

### ISSUE THREAD

**Issue by gguereque** [BiancoRoyal/node-red-contrib-opcua-server#7]
Hello,

I'm using node-red version 1.2.6 along with node.js version 14.15.2, running a flow which has an OPCUA Server. 

I followed one of the examples and just made my own OPC variables and when i first start node-red it runs just fine.

After some time (around 4 hours of working well) I get this messages on the console:

```
func readValueAsync has failed
 stack Error: expecting a valid variant value
    at assert (C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-assert\dist\source\index.ts:5:21)
    at MonitoredItem.recordValue (C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-server\src\monitored_item.js:687:5)
    at MonitoredItem._on_value_changed (C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-server\src\monitored_item.js:241:10)
    at C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-server\src\monitored_item.js:513:22
    at UAVariable.<anonymous> (C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-server\src\opcua_server.js:2147:9)
    at satisfy_callbacks (C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-address-space\src\ua_variable.js:1438:22)
    at C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-address-space\src\ua_variable.js:981:13
    at UAVariable.async_refresh_func [as refreshFunc] (C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-address-space\src\ua_variable.js:1010:9)
    at UAVariable.self.asyncRefresh (C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-address-space\src\ua_variable.js:975:26)
    at UAVariable.readValueAsync (C:\Users\ControlMTY\node_modules\node-red-contrib-opcua-server\node_modules\node-opcua-address-space\src\ua_variable.js:1443:14)
Pending transactions:  ReadRequest ReadRequest ReadRequest ReadRequest ReadRequest ReadRequest ReadRequest ReadRequest ReadRequest ReadRequest ReadRequest
```

This  seems to happen because of connection errors on the network. Is there any way to handle this errors in the compact server side?

I tried with a catch flow but it doesn't seem to work.

Thank you.

**Comment by biancode** [comment]
Hello, the package was never tested with that state of versions. You could try older states of nodejs and/or node-red. It looks like the monitored item is not valid or more the value of that item as the message informs. How are the parameters to request the monitoring and did you implement all to provide all monitoring requests well? (see node-opcua API and code for that, please) Hope that helps a bit.

**Comment by gguereque** [comment]
Hello, I copy-pased one of the examples only changing tag names and datatypes. I will check further on today and let you know if something else comes up.
